### ISSUE TITLE
Deploy to Azure not working

### ISSUE THREAD

**Issue by paul-msft** [Redislabs-Solution-Architects/acre-sql-demo#2]
The ARM template used in the Deploy to Azure link doesn't validate or deploy successfully.

Validation fails because a couple of resources are dependent on each other, causing a circular reference error. After fixing this, it seems like there are several resources in the template that are unnecessary for the demo (possibly automatically created by Azure and ended up in the template when the resource group was exported to a template). As a result, even after editing the template to remove the circular dependency, the deployment fails due to many resources being able to deploy.

**Comment by robertopc1** [comment]
Thank you @paul-msft . I'm working on changing the ARM template to bicep, I will take care of this at the same time.

**Comment by robertopc1** [comment]
Hi @paul-msft, I just uploaded the bicep file and created the arm template based on it. I've deployed the resources on my end but give it a try and let me know if you don't have any issues this time.
